language: node_js

os:
  - linux

node_js:
  - "8.9"
sudo: required

addons:
  chrome: stable

before_script:
 - yarn build

script:
 - yarn travis

after_success:
  - cd ./demo
  - yarn
  - yarn build
  - cd ../
  - chmod ugo+x ./deploy.sh
  - ./deploy.sh