language: node_js

os:
  - linux

node_js:
  - "6.9"
sudo: required

addons:
  chrome: stable

before_script:

script:
  - cd packages/ng
  - npm test
  - gulp generatedoc
  - ng build -a=demo
  - cd ../../

after_success:
  - chmod ugo+x ./deploy.sh
  - ./deploy.sh