export const translations = {
	en: {
		LU_DATE_RANGE_PICKER_CUSTOM_RANGE_LABEL: 'Other...',
		LU_DATE_RANGE_PICKER_PLACEHOLDER_FROM: 'From...',
		LU_DATE_RANGE_PICKER_PLACEHOLDER_TO: 'To...',
	},
	fr: {
		LU_DATE_RANGE_PICKER_CUSTOM_RANGE_LABEL: 'Autre...',
		LU_DATE_RANGE_PICKER_PLACEHOLDER_FROM: 'Depuis...',
		LU_DATE_RANGE_PICKER_PLACEHOLDER_TO: 'Jusqu\'à...'
	},
};
