import { BubbleIllustrationComponent } from '@lucca-front/ng/bubble-illustration';
import { Meta, moduleMetadata, StoryObj } from '@storybook/angular';
import { cleanupTemplate, generateInputs } from 'stories/helpers/stories';

export default {
	title: 'Documentation/Structure/Bubble illustration/Angular/Basic',
	argTypes: {
		illustration: {
			options: [
				'mood-angry',
				'mood-bored',
				'mood-happy',
				'mood-joyful',
				'mood-moody',
				'mood-sad',
				'mood-shoked',
				'mood-sly',
				'mood-smirking',
				'mood-surprised',
				'absence',
				'anniversary',
				'annual-rem',
				'bell',
				'bill',
				'bills',
				'bookmark',
				'books',
				'bronze',
				'building',
				'bulb',
				'calculate',
				'camera',
				'cash',
				'charts',
				'chats',
				'check',
				'chemistry',
				'clock',
				'coffee',
				'cog',
				'cup',
				'cursor',
				'diamond',
				'diversity',
				'enquete',
				'export',
				'file-2',
				'file',
				'folders',
				'gift',
				'gold',
				'growth',
				'hearth',
				'hold',
				'hourglass',
				'import',
				'link',
				'lock',
				'magnifying-glass',
				'mail',
				'marseille',
				'medical',
				'mix',
				'mobile',
				'mood',
				'nantes',
				'newbies',
				'news-feed',
				'office',
				'outside',
				'paint',
				'paper-plane',
				'paris',
				'payment-cards',
				'payslip-2',
				'payslip',
				'pen',
				'percent',
				'phone',
				'picture',
				'pin',
				'pola',
				'power',
				'puzzle',
				'recruit',
				'reload',
				'remote-work',
				'remuneration',
				'restaurant',
				'rocket',
				'save',
				'security',
				'silver',
				'sound',
				'speed',
				'stop-watch',
				'subjects',
				'tada',
				'target',
				'task',
				'thumb-up',
				'thumbtack',
				'timer',
				'tool',
				'training',
				'trash',
				'user-file',
				'user',
				'video',
				'warning',
				'widget',
			],
			control: {
				type: 'select',
			},
		},
		size: {
			options: ['S', '', 'L'],
			control: {
				type: 'select',
			},
		},
		palette: {
			options: [
				// products
				'product',
				'pagga',
				'poplee',
				'coreHR',
				'timmi',
				'cleemy',
				'cc',
				'brand',
				// states
				'neutral',
				'success',
				'warning',
				'critical',
				// decoratives
				'kiwi',
				'lime',
				'cucumber',
				'mint',
				'glacier',
				'lagoon',
				'blueberry',
				'lavender',
				'grape',
				'watermelon',
				'pumpkin',
				'pineapple',
			],
			control: {
				type: 'select',
			},
		},
	},
	decorators: [
		moduleMetadata({
			imports: [BubbleIllustrationComponent],
		}),
	],
	render: ({ palette, size, ...args }, { argTypes }) => {
		const paletteArg = palette !== 'product' ? ` palette="${palette}"` : ``;
		const sizeArg = size !== '' ? ` size="${size}"` : ``;
		return {
			template: cleanupTemplate(`<lu-bubble-illustration${sizeArg}${paletteArg}${generateInputs(args, argTypes)} />`),
		};
	},
} as Meta;

export const Basic: StoryObj<BubbleIllustrationComponent & { palette: string }> = {
	args: {
		illustration: 'anniversary',
		palette: 'product',
		action: false,
		size: '',
	},
};
