import { BubbleIllustrationComponent } from '@lucca-front/ng/bubble-illustration';
import { Meta, moduleMetadata, StoryObj } from '@storybook/angular';
import { cleanupTemplate, generateInputs } from 'stories/helpers/stories';

export default {
	title: 'Documentation/Structure/Bubble illustration/Angular/Basic',
	argTypes: {
		illustration: {
			options: [
				'moodAngry',
				'moodBored',
				'moodHappy',
				'moodJoyful',
				'moodMoody',
				'moodSad',
				'moodShoked',
				'moodSly',
				'moodSmirking',
				'moodSurprised',
				'absence',
				'anniversary',
				'awardRibbon',
				'banknote',
				'battery',
				'bell',
				'binders',
				'biscuit',
				'bookmark',
				'books',
				'bronzeMedal',
				'building',
				'bulb',
				'calculator',
				'calendar',
				'camera',
				'charts',
				'chat',
				'checkmark',
				'chemistry',
				'clipboard',
				'clock',
				'coffee',
				'cup',
				'diamond',
				'equity',
				'export',
				'file',
				'fish',
				'folder',
				'gear',
				'gift',
				'goldMedal',
				'graduate',
				'growth',
				'hearth',
				'home',
				'hourglass',
				'import',
				'invoice',
				'jigsaw',
				'link',
				'lock',
				'magnifyingGlass',
				'mail',
				'map',
				'mapPin',
				'medical',
				'megaphone',
				'mix',
				'mobile',
				'multipleReceipts',
				'newbie',
				'newsFeed',
				'office',
				'outside',
				'paint',
				'paperplane',
				'party',
				'paymentCards',
				'payslip',
				'pen',
				'percent',
				'phone',
				'picture',
				'polaroid',
				'receipt',
				'recruit',
				'reload',
				'restaurant',
				'rocket',
				'save',
				'screwdriver',
				'security',
				'silverMedal',
				'sliders',
				'speed',
				'stopwatch',
				'subjects',
				'survey',
				'target',
				'tasklist',
				'temperature',
				'thumbtack',
				'thumbUp',
				'timer',
				'trash',
				'userID',
				'video',
				'warning',
				'widget',
			],
			control: {
				type: 'select',
			},
		},
		size: {
			options: ['S', '', 'L'],
			control: {
				type: 'select',
			},
		},
		palette: {
			options: [
				// products
				'product',
				'pagga',
				'poplee',
				'coreHR',
				'timmi',
				'cleemy',
				'cc',
				'brand',
				// states
				'neutral',
				'success',
				'warning',
				'critical',
				// decoratives
				'kiwi',
				'lime',
				'cucumber',
				'mint',
				'glacier',
				'lagoon',
				'blueberry',
				'lavender',
				'grape',
				'watermelon',
				'pumpkin',
				'pineapple',
			],
			control: {
				type: 'select',
			},
		},
	},
	decorators: [
		moduleMetadata({
			imports: [BubbleIllustrationComponent],
		}),
	],
	render: ({ palette, size, ...args }, { argTypes }) => {
		const paletteArg = palette !== 'product' ? ` palette="${palette}"` : ``;
		const sizeArg = size !== '' ? ` size="${size}"` : ``;
		return {
			template: cleanupTemplate(`<lu-bubble-illustration${sizeArg}${paletteArg}${generateInputs(args, argTypes)} />`),
		};
	},
} as Meta;

export const Basic: StoryObj<BubbleIllustrationComponent & { palette: string }> = {
	args: {
		illustration: 'anniversary',
		palette: 'product',
		action: false,
		size: '',
	},
};
