import type { Rule } from '@angular-devkit/schematics';
import { CssMapper, currentSchematicContext, SchematicContextOpts } from '../lib';

// Nx need to see "@angular-devkit/schematics" in order to run this migration correctly (see https://github.com/nrwl/nx/blob/d9fed4b832bf01d1b9a44ae9e486a5e5cd2d2253/packages/nx/src/command-line/migrate/migrate.ts#L1729-L1738)
// eslint-disable-next-line @typescript-eslint/no-require-imports
require('@angular-devkit/schematics');

export default (options?: SchematicContextOpts): Rule => {

	return async (tree, context) => {
		await currentSchematicContext.init(context, options);

		await new CssMapper(
			tree,
			{
				classes: {
					"u-floatLeft": "pr-u-floatLeft",
					"u-floatRight": "pr-u-floatRight",
					"u-floatInlineStart": "pr-u-floatInlineStart",
					"u-floatInlineEnd": "pr-u-floatInlineEnd",
					"u-verticalAlignBaseline": "pr-u-verticalAlignBaseline",
					"u-verticalAlignSub": "pr-u-verticalAlignSub",
					"u-verticalAlignSuper": "pr-u-verticalAlignSuper",
					"u-verticalAlignTextTop": "pr-u-verticalAlignTextTop",
					"u-verticalAlignTextBottom": "pr-u-verticalAlignTextBottom",
					"u-verticalAlignMiddle": "pr-u-verticalAlignMiddle",
					"u-verticalAlignTop": "pr-u-verticalAlignTop",
					"u-verticalAlignBottom": "pr-u-verticalAlignBottom",
					"u-whiteSpaceNormal": "pr-u-whiteSpaceNormal",
					"u-whiteSpaceNowrap": "pr-u-whiteSpaceNowrap",
					"u-whiteSpacePreLine": "pr-u-whiteSpacePreLine",
					"u-displayBlock": "pr-u-displayBlock",
					"u-displayFlex": "pr-u-displayFlex",
					"u-displayGrid": "pr-u-displayGrid",
					"u-displayInline": "pr-u-displayInline",
					"u-displayInlineFlex": "pr-u-displayInlineFlex",
					"u-displayInlineBlock": "pr-u-displayInlineBlock",
					"u-displayInlineGrid": "pr-u-displayInlineGrid",
					"u-displayContents": "pr-u-displayContents",
					"u-displayNone": "pr-u-displayNone",
					"u-flexDirectionColumn": "pr-u-flexDirectionColumn",
					"u-flexDirectionColumnReverse": "pr-u-flexDirectionColumnReverse",
					"u-flexDirectionRow": "pr-u-flexDirectionRow",
					"u-flexDirectionRowReverse": "pr-u-flexDirectionRowReverse",
					"u-flexWrapWrap": "pr-u-flexWrapWrap",
					"u-flexWrapNowrap": "pr-u-flexWrapNowrap",
					"u-flexWrapWrapReverse": "pr-u-flexWrapWrapReverse",
					"u-justifyContentFlexStart": "pr-u-justifyContentFlexStart",
					"u-justifyContentFlexEnd": "pr-u-justifyContentFlexEnd",
					"u-justifyContentSpaceAround": "pr-u-justifyContentSpaceAround",
					"u-justifyContentSpaceBetween": "pr-u-justifyContentSpaceBetween",
					"u-justifyContentSpaceEvenly": "pr-u-justifyContentSpaceEvenly",
					"u-justifyContentCenter": "pr-u-justifyContentCenter",
					"u-alignItemsFlexStart": "pr-u-alignItemsFlexStart",
					"u-alignItemsFlexEnd": "pr-u-alignItemsFlexEnd",
					"u-alignItemsBaseline": "pr-u-alignItemsBaseline",
					"u-alignItemsStretch": "pr-u-alignItemsStretch",
					"u-alignItemsCenter": "pr-u-alignItemsCenter",
					"u-flexGrow0": "pr-u-flexGrow0",
					"u-flexGrow1": "pr-u-flexGrow1",
					"u-flexShrink0": "pr-u-flexShrink0",
					"u-flexShrink1": "pr-u-flexShrink1",
					"u-flexBasis0": "pr-u-flexBasis0",
					"u-flexBasisAuto": "pr-u-flexBasisAuto",
					"u-orderMinus1": "pr-u-orderMinus1",
					"u-order1": "pr-u-order1",
					"u-alignSelfFlexStart": "pr-u-alignSelfFlexStart",
					"u-alignSelfFlexEnd": "pr-u-alignSelfFlexEnd",
					"u-alignSelfBaseline": "pr-u-alignSelfBaseline",
					"u-alignSelfStretch": "pr-u-alignSelfStretch",
					"u-alignSelfCenter": "pr-u-alignSelfCenter",
					"u-positionAbsolute": "pr-u-positionAbsolute",
					"u-positionRelative": "pr-u-positionRelative",
					"u-positionStatic": "pr-u-positionStatic",
					"u-positionFixed": "pr-u-positionFixed",
					"u-positionSticky": "pr-u-positionSticky",
					"u-width100%": "pr-u-width100%",
					"u-widthFitContent": "pr-u-widthFitContent",
					"u-height100%": "pr-u-height100%",
					"u-heightFitContent": "pr-u-heightFitContent",
					"u-minWidth0": "pr-u-minWidth0",
					"u-minHeight0": "pr-u-minHeight0",
					"u-inlineSize100%": "pr-u-inlineSize100%",
					"u-inlineSizeFitContent": "pr-u-inlineSizeFitContent",
					"u-blockSize100%": "pr-u-blockSize100%",
					"u-blockSizeFitContent": "pr-u-blockSizeFitContent",
					"u-minInlineSize0": "pr-u-minInlineSize0",
					"u-minBlockSize0": "pr-u-minBlockSize0",
					"u-maxInlineSize100%": "pr-u-maxInlineSize100%",
					"u-maxInlineSizeFitContent": "pr-u-maxInlineSizeFitContent",
					"u-visibilityVisible": "pr-u-visibilityVisible",
					"u-visibilityHidden": "pr-u-visibilityHidden",
					"u-visibilityCollapse": "pr-u-visibilityCollapse",
					"u-fontWeight400": "pr-u-fontWeight400",
					"u-fontWeight600": "pr-u-fontWeight600",
					"u-fontWeight700": "pr-u-fontWeight700",
					"u-fontWeight900": "pr-u-fontWeight900",
					"u-fontWeightNormal": "pr-u-fontWeightNormal",
					"u-fontWeightBold": "pr-u-fontWeightBold",
					"u-fontStyleNormal": "pr-u-fontStyleNormal",
					"u-fontStyleItalic": "pr-u-fontStyleItalic",
					"u-pointerEventsNone": "pr-u-pointerEventsNone",
					"u-pointerEventsAuto": "pr-u-pointerEventsAuto",
					"u-cursorPointer": "pr-u-cursorPointer",
					"u-cursorAuto": "pr-u-cursorAuto",
					"u-textAlignLeft": "pr-u-textAlignLeft",
					"u-textAlignCenter": "pr-u-textAlignCenter",
					"u-textAlignRight": "pr-u-textAlignRight",
					"u-textAlignStart": "pr-u-textAlignStart",
					"u-textAlignEnd": "pr-u-textAlignEnd",
					"u-textDecorationUnderline": "pr-u-textDecorationUnderline",
					"u-textDecorationLineThrough": "pr-u-textDecorationLineThrough",
					"u-textDecorationNone": "pr-u-textDecorationNone",
					"u-overflowHidden": "pr-u-overflowHidden",
					"u-overflowAuto": "pr-u-overflowAuto",
					"u-overflowVisible": "pr-u-overflowVisible",
					"u-overflowScroll": "pr-u-overflowScroll",
					"u-scrollBehaviorAuto": "pr-u-scrollBehaviorAuto",
					"u-scrollBehaviorSmooth": "pr-u-scrollBehaviorSmooth",
					"u-onlyPrintDisplayBlock": "pr-u-onlyPrintDisplayBlock",
					"u-onlyPrintDisplayFlex": "pr-u-onlyPrintDisplayFlex",
					"u-onlyPrintDisplayGrid": "pr-u-onlyPrintDisplayGrid",
					"u-onlyPrintDisplayInline": "pr-u-onlyPrintDisplayInline",
					"u-onlyPrintDisplayInlineFlex": "pr-u-onlyPrintDisplayInlineFlex",
					"u-onlyPrintDisplayInlineBlock": "pr-u-onlyPrintDisplayInlineBlock",
					"u-onlyPrintDisplayInlineGrid": "pr-u-onlyPrintDisplayInlineGrid",
					"u-onlyPrintDisplayContents": "pr-u-onlyPrintDisplayContents",
					"u-onlyPrintDisplayNone": "pr-u-onlyPrintDisplayNone",
					"u-textXS": "pr-u-textXS",
					"u-textS": "pr-u-textS",
					"u-textM": "pr-u-textM",
					"u-textL": "pr-u-textL",
					"u-textXL": "pr-u-textXL",
					"u-textXXL": "pr-u-textXXL",
					"u-textXXXL": "pr-u-textXXXL",
					"u-borderRadiusM": "pr-u-borderRadiusM",
					"u-borderRadiusL": "pr-u-borderRadiusL",
					"u-borderRadiusXL": "pr-u-borderRadiusXL",
					"u-borderRadiusFull": "pr-u-borderRadiusFull",
					"u-borderTopLeftRadiusM": "pr-u-borderTopLeftRadiusM",
					"u-borderTopLeftRadiusL": "pr-u-borderTopLeftRadiusL",
					"u-borderTopLeftRadiusXL": "pr-u-borderTopLeftRadiusXL",
					"u-borderTopLeftRadiusFull": "pr-u-borderTopLeftRadiusFull",
					"u-borderTopRightRadiusM": "pr-u-borderTopRightRadiusM",
					"u-borderTopRightRadiusL": "pr-u-borderTopRightRadiusL",
					"u-borderTopRightRadiusXL": "pr-u-borderTopRightRadiusXL",
					"u-borderTopRightRadiusFull": "pr-u-borderTopRightRadiusFull",
					"u-borderBottomLeftRadiusM": "pr-u-borderBottomLeftRadiusM",
					"u-borderBottomLeftRadiusL": "pr-u-borderBottomLeftRadiusL",
					"u-borderBottomLeftRadiusXL": "pr-u-borderBottomLeftRadiusXL",
					"u-borderBottomLeftRadiusFull": "pr-u-borderBottomLeftRadiusFull",
					"u-borderBottomRightRadiusM": "pr-u-borderBottomRightRadiusM",
					"u-borderBottomRightRadiusL": "pr-u-borderBottomRightRadiusL",
					"u-borderBottomRightRadiusXL": "pr-u-borderBottomRightRadiusXL",
					"u-borderBottomRightRadiusFull": "pr-u-borderBottomRightRadiusFull",
					"u-borderStartStartRadiusM": "pr-u-borderStartStartRadiusM",
					"u-borderStartStartRadiusL": "pr-u-borderStartStartRadiusL",
					"u-borderStartStartRadiusXL": "pr-u-borderStartStartRadiusXL",
					"u-borderStartStartRadiusFull": "pr-u-borderStartStartRadiusFull",
					"u-borderStartEndRadiusM": "pr-u-borderStartEndRadiusM",
					"u-borderStartEndRadiusL": "pr-u-borderStartEndRadiusL",
					"u-borderStartEndRadiusXL": "pr-u-borderStartEndRadiusXL",
					"u-borderStartEndRadiusFull": "pr-u-borderStartEndRadiusFull",
					"u-borderEndStartRadiusM": "pr-u-borderEndStartRadiusM",
					"u-borderEndStartRadiusL": "pr-u-borderEndStartRadiusL",
					"u-borderEndStartRadiusXL": "pr-u-borderEndStartRadiusXL",
					"u-borderEndStartRadiusFull": "pr-u-borderEndStartRadiusFull",
					"u-borderEndEndRadiusM": "pr-u-borderEndEndRadiusM",
					"u-borderEndEndRadiusL": "pr-u-borderEndEndRadiusL",
					"u-borderEndEndRadiusXL": "pr-u-borderEndEndRadiusXL",
					"u-borderEndEndRadiusFull": "pr-u-borderEndEndRadiusFull",
					"u-textCritical": "pr-u-textCritical",
					"u-textError": "pr-u-textError",
					"u-textWarning": "pr-u-textWarning",
					"u-textSuccess": "pr-u-textSuccess",
					"u-textSuccessContrasted": "pr-u-textSuccessContrasted",
					"u-textWarningContrasted": "pr-u-textWarningContrasted",
					"u-textBrand": "pr-u-textBrand",
					"u-textBrandContrasted": "pr-u-textBrandContrasted",
					"u-textNeutral": "pr-u-textNeutral",
					"u-textNavigation": "pr-u-textNavigation",
					"u-textProduct": "pr-u-textProduct",
					"u-textPagga": "pr-u-textPagga",
					"u-textPoplee": "pr-u-textPoplee",
					"u-textCoreHR": "pr-u-textCoreHR",
					"u-textTimmi": "pr-u-textTimmi",
					"u-textCleemy": "pr-u-textCleemy",
					"u-textCc": "pr-u-textCc",
					"u-textKiwi": "pr-u-textKiwi",
					"u-textLime": "pr-u-textLime",
					"u-textCucumber": "pr-u-textCucumber",
					"u-textMint": "pr-u-textMint",
					"u-textGlacier": "pr-u-textGlacier",
					"u-textLagoon": "pr-u-textLagoon",
					"u-textBlueberry": "pr-u-textBlueberry",
					"u-textLavender": "pr-u-textLavender",
					"u-textGrape": "pr-u-textGrape",
					"u-textWatermelon": "pr-u-textWatermelon",
					"u-textPumpkin": "pr-u-textPumpkin",
					"u-textPineapple": "pr-u-textPineapple",
					"u-textLucca": "pr-u-textLucca",
					"u-textGrey": "pr-u-textGrey",
					"u-textPrimary": "pr-u-textPrimary",
					"u-textSecondary": "pr-u-textSecondary",
					"u-animatedFadeIn": "pr-u-animatedFadeIn",
					"u-animatedFadeOut": "pr-u-animatedFadeOut",
					"u-animatedScaleIn": "pr-u-animatedScaleIn",
					"u-animatedScaleOut": "pr-u-animatedScaleOut",
					"u-animatedScaleInTop": "pr-u-animatedScaleInTop",
					"u-animatedScaleOutTop": "pr-u-animatedScaleOutTop",
					"u-animatedScaleInRight": "pr-u-animatedScaleInRight",
					"u-animatedScaleOutRight": "pr-u-animatedScaleOutRight",
					"u-animatedScaleInBottom": "pr-u-animatedScaleInBottom",
					"u-animatedScaleOutBottom": "pr-u-animatedScaleOutBottom",
					"u-animatedScaleInLeft": "pr-u-animatedScaleInLeft",
					"u-animatedScaleOutLeft": "pr-u-animatedScaleOutLeft",
					"u-animatedSlideIn": "pr-u-animatedSlideIn",
					"u-animatedSlideInTop": "pr-u-animatedSlideInTop",
					"u-animatedSlideOut": "pr-u-animatedSlideOut",
					"u-animatedSlideOutTop": "pr-u-animatedSlideOutTop",
					"u-animatedSlideInRight": "pr-u-animatedSlideInRight",
					"u-animatedSlideOutRight": "pr-u-animatedSlideOutRight",
					"u-animatedSlideInBottom": "pr-u-animatedSlideInBottom",
					"u-animatedSlideOutBottom": "pr-u-animatedSlideOutBottom",
					"u-animatedSlideInLeft": "pr-u-animatedSlideInLeft",
					"u-animatedSlideOutLeft": "pr-u-animatedSlideOutLeft",
					"u-animatedShake": "pr-u-animatedShake",
					"u-animatedPulse": "pr-u-animatedPulse",
					"u-mask": "pr-u-mask",
					"u-clearfix": "pr-u-clearfix",
					"u-clearBoth": "pr-u-clearBoth",
					"u-clear": "pr-u-clear",
					"u-clearInlineStart": "pr-u-clearInlineStart",
					"u-clearLeft": "pr-u-clearLeft",
					"u-clearInlineEnd": "pr-u-clearInlineEnd",
					"u-clearRight": "pr-u-clearRight",
					"u-listReset": "pr-u-listReset",
					"u-descriptionListReset": "pr-u-descriptionListReset",
					"u-summaryReset": "pr-u-summaryReset",
					"u-buttonReset": "pr-u-buttonReset",
					"u-ellipsis": "pr-u-ellipsis",
					"u-h1": "pr-u-h1",
					"u-h2": "pr-u-h2",
					"u-h3": "pr-u-h3",
					"u-h4": "pr-u-h4",
					"u-h5": "pr-u-h5",
					"u-h6": "pr-u-h6",
					"u-bodyM": "pr-u-bodyM",
					"u-bodyS": "pr-u-bodyS",
					"u-bodyXS": "pr-u-bodyXS",
					"u-textLeft": "pr-u-textLeft",
					"u-textRight": "pr-u-textRight",
					"u-textCenter": "pr-u-textCenter",
					"u-textLight": "pr-u-textLight",
					"u-textPlaceholder": "pr-u-textPlaceholder",
					"u-textDefault": "pr-u-textDefault",
					"u-fontWeightRegular": "pr-u-fontWeightRegular",
					"u-fontWeightSemiBold": "pr-u-fontWeightSemiBold",
					"u-noSpinButtons": "pr-u-noSpinButtons",
					"u-fontFamily": "pr-u-fontFamily",
					"u-fontFamilyCursive": "pr-u-fontFamilyCursive",
					"u-fontFamilyBrand": "pr-u-fontFamilyBrand",
					"u-inset0": "pr-u-inset0",
					"u-insetReset": "pr-u-insetReset",
					"u-top0": "pr-u-top0",
					"u-topReset": "pr-u-topReset",
					"u-bottom0": "pr-u-bottom0",
					"u-bottomReset": "pr-u-bottomReset",
					"u-left0": "pr-u-left0",
					"u-leftReset": "pr-u-leftReset",
					"u-right0": "pr-u-right0",
					"u-rightReset": "pr-u-rightReset",
					"u-marginInline0": "pr-u-marginInline0",
					"u-paddingInline0": "pr-u-paddingInline0",
					"u-insetInline0": "pr-u-insetInline0",
					"u-marginBlock0": "pr-u-marginBlock0",
					"u-paddingBlock0": "pr-u-paddingBlock0",
					"u-insetBlock0": "pr-u-insetBlock0",
					"u-marginBlock-start0": "pr-u-marginBlock-start0",
					"u-paddingBlock-start0": "pr-u-paddingBlock-start0",
					"u-insetBlock-start0": "pr-u-insetBlock-start0",
					"u-marginBlock-end0": "pr-u-marginBlock-end0",
					"u-paddingBlock-end0": "pr-u-paddingBlock-end0",
					"u-insetBlock-end0": "pr-u-insetBlock-end0",
					"u-marginInline-start0": "pr-u-marginInline-start0",
					"u-paddingInline-start0": "pr-u-paddingInline-start0",
					"u-insetInline-start0": "pr-u-insetInline-start0",
					"u-marginInline-end0": "pr-u-marginInline-end0",
					"u-paddingInline-end0": "pr-u-paddingInline-end0",
					"u-insetInline-end0": "pr-u-insetInline-end0",
					"u-prefersContrastMore": "pr-u-prefersContrastMore",
					"u-border0" : "pr-u-border0",
					"u-borderBottom0" : "pr-u-borderBottom0",
					"u-borderTop0" : "pr-u-borderTop0",
					"u-borderRight0" : "pr-u-borderRight0",
					"u-borderLeft0" : "pr-u-borderLeft0",
					"u-borderInline0" : "pr-u-borderInline0",
					"u-borderBlock0" : "pr-u-borderBlock0",
					"u-borderBlockEnd0" : "pr-u-borderBlockEnd0",
					"u-borderBlockStart0" : "pr-u-borderBlockStart0",
					"u-borderInlineStart0" : "pr-u-borderInlineStart0",
					"u-borderInlineEnd0" : "pr-u-borderInlineEnd0",
				},
				variables: {},
				mixins: {}
			},
			{}
		).run();
	};
};
