export const MAIN_LAYOUT_ILLUSTRATION_START_END = [
	'generic/coffee-01',
	'generic/cookie-01',
	'generic/error-01',
	'generic/glasses-01',
	'generic/plant-01',
	'generic/plant-02',
	'generic/plug-01',
	'generic/polaroids-01',
	'generic/post-its-01',
	'generic/success-01',
	'generic/tea-01',
] as const;
export type MainLayoutIllustrationStartEnd = (typeof MAIN_LAYOUT_ILLUSTRATION_START_END)[number] | string;

export const MAIN_LAYOUT_ILLUSTRATION_END_START = [
	'cleemy/accounting-01',
	'cleemy/crumpled-paper-pencil-shavings',
	'cleemy/crumpled-papers',
	'cleemy/expenses-01',
	'cleemy/expenses-02',
	'cleemy/finance-01',
	'cleemy/finance-hat-sunglasses',
	'cleemy/payment-01',
	'cleemy/procurement-01',
	'error/coffee-01',
	'error/lock-01',
	'error/plug-01',
	'generic/lock-broken-key',
	'generic/plant-03',
	'lucca/lucca-01',
	'pagga/compensation-01',
	'pagga/mealvoucher-01',
	'pagga/mealvoucher-02',
	'pagga/mealvoucher-03',
	'pagga/mealvoucher-icecream',
	'pagga/payroll-01',
	'pagga/payslips-01',
	'pagga/wizard-01',
	'poplee/core-hr-01',
	'poplee/engagement-01',
	'poplee/performance-01',
	'poplee/talent-01',
	'poplee/training-01',
	'success/party-favor-01',
	'timmi/absences-01',
	'timmi/office-01',
	'timmi/projects-01',
	'timmi/time-and-activities-01',
	'timmi/timesheet-01',
] as const;
export type MainLayoutIllustrationEndStart = (typeof MAIN_LAYOUT_ILLUSTRATION_END_START)[number] | string;
