/**
 * Frozen seed list of deprecated CSS API names.
 *
 * This exists ONLY for deprecated names that are generated by SCSS loops and
 * therefore cannot carry an inline `/* @deprecated *\/` comment in the source
 * (the primary, zero-maintenance mechanism — see generate.js `readDeprecatedComments`).
 *
 * Do not grow this list for new deprecations: mark those at the source with a
 * loud `/* @deprecated *\/` comment on the declaration instead. This list is a
 * one-time snapshot of the pre-existing deprecations that live only in loops.
 */

'use strict';

/**
 * Custom-property names that are deprecated. Matched against the full property
 * name including leading dashes (e.g. `--colors-white-color`).
 * @type {RegExp[]}
 */
const DEPRECATED_VARIABLE_PATTERNS = [
	/^--colors-/, // superseded by --palettes-*
	/^--sizes-/, // superseded by --pr-t-font-* tokens
	/^--commons-borderRadius-/, // superseded by --pr-t-border-radius-*
];

/**
 * Utility-class deprecations. Each rule matches a class name (without the
 * leading dot, e.g. `pr-u-marginTop100`) and optionally computes a suggested
 * replacement from the matched name.
 * @type {{ test: RegExp, replacement?: (name: string) => string | undefined }[]}
 */
const DEPRECATED_CLASS_RULES = [
	// Bare `u-` prefix is entirely deprecated in favour of `pr-u-`.
	{
		test: /^u-/,
		replacement: (name) => `pr-${name}`,
	},
	// Physical-direction spacings: use logical equivalents (inline/block) instead.
	{
		test: /^pr-u-(margin|padding|border|inset)(Top|Bottom|Left|Right)[A-Z0-9]/,
	},
	// Physical single-side inset resets.
	{
		test: /^pr-u-(top|bottom|left|right)(0|Reset)?$/,
	},
	// `float`/`clear` left/right are physical; logical inline-start/end preferred.
	{
		test: /^pr-u-(float|clear)(Left|Right)$/,
	},
	// textAlign left/right are physical; use start/end.
	{
		test: /^pr-u-textAlign(Left|Right)$/,
		replacement: (name) => (name.endsWith('Left') ? 'pr-u-textAlignStart' : 'pr-u-textAlignEnd'),
	},
	// Hand-written legacy text utilities (index.scss) with no derivable modern
	// twin. Palette colour classes (`pr-u-textBrand` etc.) are NOT listed here —
	// they are derived from their `pr-u-colorText<Palette>` twins in generate.js.
	{ test: /^pr-u-textLeft$/, replacement: () => 'pr-u-textAlignStart' },
	{ test: /^pr-u-textRight$/, replacement: () => 'pr-u-textAlignEnd' },
	{ test: /^pr-u-textCenter$/, replacement: () => 'pr-u-textAlignCenter' },
	{ test: /^pr-u-textLight$/ },
	{ test: /^pr-u-textPlaceholder$/ },
	{ test: /^pr-u-textDefault$/ },
	// Deprecated font-size utility classes generated by the deprecated `sizes` mixin.
	{
		test: /^pr-u-text(XS|S|M|L|XL|XXL|XXXL)$/,
	},
	// Deprecated border-radius utilities generated by the deprecated `borderRadius`
	// mixin (values M / L / XL, plus per-corner variants). The token-based
	// `pr-u-borderRadius<Token>` classes are NOT deprecated.
	{
		test: /^pr-u-border([A-Z][a-z]+[A-Z][a-z]+)?Radius(M|L|XL)$/,
	},
];

/**
 * @param {string} varName full custom-property name including leading dashes
 * @returns {boolean}
 */
function isDeprecatedVariable(varName) {
	return DEPRECATED_VARIABLE_PATTERNS.some((re) => re.test(varName));
}

/**
 * @param {string} className class name without the leading dot
 * @returns {{ deprecated: true, replacement?: string } | undefined}
 */
function classDeprecation(className) {
	for (const rule of DEPRECATED_CLASS_RULES) {
		if (rule.test.test(className)) {
			const replacement = rule.replacement ? rule.replacement(className) : undefined;
			return replacement ? { deprecated: true, replacement } : { deprecated: true };
		}
	}
	return undefined;
}

module.exports = { isDeprecatedVariable, classDeprecation };
