/**
 * Frozen seed list of deprecated CSS API names.
 *
 * This exists ONLY for deprecated names that are generated by SCSS loops and
 * therefore cannot carry an inline `/* @deprecated *\/` comment in the source
 * (the primary, zero-maintenance mechanism — see generate.js `readDeprecatedComments`).
 *
 * Do not grow this list for new deprecations: mark those at the source with a
 * loud `/* @deprecated *\/` comment on the declaration instead. This list is a
 * one-time snapshot of the pre-existing deprecations that live only in loops.
 */

'use strict';

/**
 * Custom-property names that are deprecated. Matched against the full property
 * name including leading dashes (e.g. `--colors-white-color`).
 * @type {RegExp[]}
 */
const DEPRECATED_VARIABLE_PATTERNS = [
	/^--colors-/, // superseded by --palettes-*
	/^--sizes-/, // superseded by --pr-t-font-* tokens
	/^--commons-borderRadius-/, // superseded by --pr-t-border-radius-*
];

/**
 * Utility-class deprecations. Each rule matches a class name (without the
 * leading dot, e.g. `pr-u-marginTop100`) and optionally computes a suggested
 * replacement from the matched name.
 * @type {{ test: RegExp, replacement?: (name: string) => string | undefined }[]}
 */
// Physical box-side → CSS logical property segment.
const PHYSICAL_TO_LOGICAL = { Top: 'BlockStart', Bottom: 'BlockEnd', Left: 'InlineStart', Right: 'InlineEnd' };
// Physical single-side inset → logical inset class stem.
const PHYSICAL_TO_INSET = { top: 'insetBlockStart', bottom: 'insetBlockEnd', left: 'insetInlineStart', right: 'insetInlineEnd' };

const DEPRECATED_CLASS_RULES = [
	// Bare `u-` prefix is entirely deprecated in favour of `pr-u-`.
	{
		test: /^u-/,
		replacement: (name) => `pr-${name}`,
	},
	// Physical-direction spacings: use logical equivalents (inline/block) instead.
	// e.g. pr-u-marginTop100 → pr-u-marginBlockStart100. The suffix is a spacing
	// key (digits or `Auto`); this deliberately excludes border-*-radius corner
	// classes like pr-u-borderTopLeftRadiusM (owned by the border-radius rule).
	{
		test: /^pr-u-(margin|padding|border|inset)(Top|Bottom|Left|Right)(\d+|Auto)$/,
		replacement: (name) => {
			const m = /^pr-u-(margin|padding|border|inset)(Top|Bottom|Left|Right)(\d+|Auto)$/.exec(name);
			return m ? `pr-u-${m[1]}${PHYSICAL_TO_LOGICAL[m[2]]}${m[3]}` : undefined;
		},
	},
	// Physical single-side insets/resets. Both `pr-u-top0` and `pr-u-topReset`
	// set `top: 0`, so both map to the logical `pr-u-insetBlockStart0`.
	{
		test: /^pr-u-(top|bottom|left|right)(0|Reset)?$/,
		replacement: (name) => {
			const m = /^pr-u-(top|bottom|left|right)(0|Reset)?$/.exec(name);
			return m ? `pr-u-${PHYSICAL_TO_INSET[m[1]]}0` : undefined;
		},
	},
	// `float`/`clear` left/right are physical; logical inline-start/end preferred.
	{
		test: /^pr-u-(float|clear)(Left|Right)$/,
		replacement: (name) => {
			const m = /^pr-u-(float|clear)(Left|Right)$/.exec(name);
			return m ? `pr-u-${m[1]}${m[2] === 'Left' ? 'InlineStart' : 'InlineEnd'}` : undefined;
		},
	},
	// textAlign left/right are physical; use start/end.
	{
		test: /^pr-u-textAlign(Left|Right)$/,
		replacement: (name) => (name.endsWith('Left') ? 'pr-u-textAlignStart' : 'pr-u-textAlignEnd'),
	},
	// Hand-written legacy text utilities (index.scss) with no derivable modern
	// twin. Palette colour classes (`pr-u-textBrand` etc.) are NOT listed here —
	// they are derived from their `pr-u-colorText<Palette>` twins in generate.js.
	{ test: /^pr-u-textLeft$/, replacement: () => 'pr-u-textAlignStart' },
	{ test: /^pr-u-textRight$/, replacement: () => 'pr-u-textAlignEnd' },
	{ test: /^pr-u-textCenter$/, replacement: () => 'pr-u-textAlignCenter' },
	{ test: /^pr-u-textLight$/ },
	{ test: /^pr-u-textPlaceholder$/ },
	{ test: /^pr-u-textDefault$/ },
	// Deprecated font-size utility classes generated by the deprecated `sizes` mixin.
	{
		test: /^pr-u-text(XS|S|M|L|XL|XXL|XXXL)$/,
	},
	// Deprecated border-radius utilities generated by the deprecated `borderRadius`
	// mixin. Corner variants exist for M / L / XL / Full; the corner-less form is
	// deprecated only for M / L / XL — `pr-u-borderRadiusFull` (and other tokens
	// like Structure/Default) are the modern token classes and stay non-deprecated.
	{
		test: /^pr-u-border(?:[A-Z][a-z]+[A-Z][a-z]+Radius(?:M|L|XL|Full)|Radius(?:M|L|XL))$/,
	},
];

/**
 * @param {string} varName full custom-property name including leading dashes
 * @returns {boolean}
 */
function isDeprecatedVariable(varName) {
	return DEPRECATED_VARIABLE_PATTERNS.some((re) => re.test(varName));
}

/**
 * @param {string} className class name without the leading dot
 * @returns {{ deprecated: true, replacement?: string } | undefined}
 */
function classDeprecation(className) {
	for (const rule of DEPRECATED_CLASS_RULES) {
		if (rule.test.test(className)) {
			const replacement = rule.replacement ? rule.replacement(className) : undefined;
			return replacement ? { deprecated: true, replacement } : { deprecated: true };
		}
	}
	return undefined;
}

module.exports = { isDeprecatedVariable, classDeprecation };
